/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kml.reader;

import java.io.IOException;
import java.io.InputStream;

import javax.xml.namespace.QName;
import javax.xml.parsers.ParserConfigurationException;

import org.geotools.kml.KML;
import org.geotools.kml.v22.KMLConfiguration;
import org.geotools.xsd.Parser;
import org.geotools.xsd.StreamingParser;
import org.opengis.feature.simple.SimpleFeature;
import org.xml.sax.SAXException;

public class KMLHandler {
    public static SimpleFeature getSimpleFeatureFromStream(InputStream inputStream) throws IOException, SAXException, ParserConfigurationException {

        if (inputStream == null) return null;

        Parser parser = new Parser(new KMLConfiguration());

        return (SimpleFeature) parser.parse(inputStream);
    }

    public static StreamingParser getStreamingParserFromStream(InputStream inputStream, QName qName) throws IOException, SAXException, ParserConfigurationException {

        if (inputStream == null) return null;

        if (qName == null) return new StreamingParser(new KMLConfiguration(), inputStream, KML.Feature);

        return new StreamingParser(new KMLConfiguration(), inputStream, qName);
    }
}
