/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kml.reader;

import org.junit.Test;
import org.xml.sax.SAXException;

import static org.junit.Assert.*;

import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;

public class KMLHandlerTest {
    @Test
    public void test_getSimpleFeatureFromStream() throws IOException, SAXException, ParserConfigurationException {
        assertNull("getSimpleFeatureFromStream should return null", KMLHandler.getSimpleFeatureFromStream(null));
    }

    @Test
    public void test_getStreamingParserFromStream() throws IOException, SAXException, ParserConfigurationException {
        assertNull("getSimpleFeatureFromStream should return null", KMLHandler.getStreamingParserFromStream(null, null));
    }
}
